version: "3.9"
services:
  atsws:
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    image: $CI_REGISTRY_IMAGE:prod-latest
    container_name: atsws
    restart: always
    expose:
      - "80"
    networks:
      liliumnet:
        ipv4_address: 192.168.1.6

networks:
  liliumnet:
    external:
      name: liliumnet
